Warnings reorg
mmp/vice pull request #154
Opened 2024-03-22 11:25 UTC by mmp

2024-03-23 04:15 UTC, checkandmate1 requested changes
We're still encountering SPC's overriding each other with a new one. For example, if there is an RF on an aircraft, and an EM is added, that EM Will override the previous RF,

2024-03-23 04:27 UTC, checkandmate1 commented on stars.go
> +	var warnings []string
When `warnings` is created it never accounts for the warnings that are not in the string `SPCOveride`. What ends up happening is that only the warning that is in SPCOverride is shown as a warning. Either converting SPCOverride to a []string, so that it can store multiple warnings, or replacing `warnings` with `state.warnings` so that the previous warnings can save. Then just having some logic to prevent duplicate entries:
```go
if index := slices.Index(state.Warnings, state.SPCOverride); index != -1 {
		state.Warnings = append(state.Warnings[:index], state.Warnings[index+1:]...)
	} else if ac.Squawk == Squawk(0o7700) || state.SPCOverride == "EM" {
state.Warnings = append(state.Warnings, "EM")
} // etc...
```

2024-03-23 04:27 UTC, checkandmate1 commented on stars.go
> +func (sp *STARSPane) getWarnings(ctx *PaneContext, ac *Aircraft) []string {
I do think `getWarnings` is a good thing to have, just to clean `formatDatablocks` up a bit

2024-03-23 04:28 UTC, checkandmate1 commented on stars.go
> +		warnings = append(warnings, "MI")
I think MI should be replaced with LL (lost link). I got told that MI was also yellow, but I'm not 100% sure.

2024-03-23 15:50 UTC, mmp commented on stars.go
> +	var warnings []string
Ah, got it. I changed to a `map[string]interface{}` to be able maintain multiple overrides and also added logic so that specifying an active override toggles it back off.

2024-03-23 15:52 UTC, mmp commented on stars.go
> +		warnings = append(warnings, "MI")
p. 2-66 of the STARS manual has 7400 for LL and 7777 for MI.

The change I pushed reworks handling of SPCs significantly both making it simpler and more extensible (I think). I left off making MI yellow since that will take some further work to the datablock formatting code. But I think the `SPC` struct there could just be extended to hold a color for each one and then we could access that in the datablock code in the future...

2024-03-23 15:57 UTC, checkandmate1 commented on stars.go
> +	var warnings []string
Changing it to a map may cause some formatting issues, AFAIK maps aren't ordered like slices/ arrays.

2024-03-23 16:01 UTC, mmp commented on stars.go
> +	var warnings []string
Indeed, maps give the keys in random order, but everywhere it's used it goes through `SortedMapKeys` so they will come out in a consistent order.

2024-03-25 13:42 UTC, checkandmate1 approved these changes
This all looks good! Using a map[string]interface{} is definitely the way to go (also naturally protects against duplicate entries)

2024-03-27 13:23 UTC, merged