Fix handling of various CRDA commands
mmp/vice pull request #159
Opened 2024-03-24 16:03 UTC by mmp

- Correctly parse optional airports (fixes #39).
- Use controller default airport when airport is unspecified (for commands that use it.)
- Add [MF]NP(airport)(#) to toggle ghosts for a runway pair
- Fix CRDA slew commands to match the specification
- Added a few STARS error codes used for CRDA
- Updated docs

2024-03-25 13:47 UTC, checkandmate1 commented on errors.go
> +	ErrSTARSIllegalFunction   = NewSTARSError("ILL FNCT")
This should be here, but also `ILL FUNC` is also a thing as well. (5-161). Not exactly sure what the difference is.

2024-03-25 14:52 UTC, checkandmate1 commented on stars.go
> +						airport = ctrl.DefaultAirport[1:] // drop leading "K"
I already managed to break it. Entering the command `MULTI FUNC NPEWR1` seemed to crash it because the slice [1:0] was out of bounds. I'm not 100% sure how this command works, but it is good that I found this bug out

2024-03-25 14:53 UTC, checkandmate1 commented
Where in the STARS manual is the NP command?

2024-03-25 15:07 UTC, checkandmate1 requested changes
Using the command `MULTI FUNC NEWR1T` gave an `ILL PARAM`, so that may be something to look into. Also, I can't get the NP command to work either.

2024-03-27 13:29 UTC, mmp commented
> Where in the STARS manual is the NP command?

p6-22, at least in the copy I have. ("Toggle display of Ghost data blocks for specified runway pair")

2024-03-27 14:25 UTC, mmp commented
> Using the command `MULTI FUNC NEWR1T` gave an `ILL PARAM`, so that may be something to look into. Also, I can't get the NP command to work either.

Assuming you mean to enable tie mode, I believe it should be `[MULTIFUNC]NPEWR 1T` (8-11) otherwise it's `[MULTIFUNC]NEWR 1E` to enable ghosts (6-23). So I think that's a valid error.

2024-03-27 14:28 UTC, mmp commented on stars.go
> +						airport = ctrl.DefaultAirport[1:] // drop leading "K"
I'm not able to reproduce this. I'm wondering if you tried with a saved session rather than starting a new one. (If the saved session was from before `Controller` `DefaultAirport` was introduced then it would be unset and this would happen. In the latest version we validate that when scenarios are loaded when vice launches: https://github.com/mmp/vice/blob/463be18bacddf1a9dea6e1c7fbecd02d011561f7/scenario.go#L298.

2024-03-29 19:41 UTC, merged